// Generated by LiveScript 1.2.0
(function(){
  var app;
  angular.module('MSDirectives', []).directive('msSkill', function(){
    return {
      restrict: 'E',
      scope: true,
      templateUrl: 'partials/skill.html',
      controller: function($scope, $attrs){
        $scope.label = $attrs.label, $scope.id = $attrs.id;
        $scope.activated = $scope.skills[$scope.label];
        return $scope.click = function(){
          $scope.activated = !$scope.activated;
          return $scope.skills[$scope.label] = $scope.activated;
        };
      }
    };
  });
  app = angular.module('masteries', ['angularLocalStorage', 'MSDirectives']);
  app.controller('msCtrl', function($scope, storage){
    storage.bind($scope, 'skills');
    $scope.skills || ($scope.skills = {});
    return $scope.$watch('skills', function(){
      return console.log($scope.skills);
    }, true);
  });
}).call(this);
